Repository 404-bug-not-found/100_percent_capstone, pull requests merged in 2021-05, with the labels that each got.

#28 Feature/cicd pipeline0508
  Dockerfile
  heroku.yml
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplication.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/DatabaseConfig.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyDTO.java
  src/main/resources/application-heroku.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplicationTests.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
Labels: Team1

#29 Feature/cicd pipeline0508
  Dockerfile
  src/main/resources/application-heroku.properties
  src/main/resources/application-local.properties
Labels: Team1

#31 Added jacoco setup to build.gradle
  build.gradle
Labels: Team1

#32 Update gradle.yml
  .github/workflows/gradle.yml
  build.gradle
Labels: Team1

#33 Feature/issue 4 rest documentation
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
Labels: Team2

#36 Issue 34 jacoco code coverage
  build.gradle
  lombok.config
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplication.java
  src/main/java/com/hundred/percent/capstone/Invoicify/config/DatabaseConfig.java
  src/main/java/com/hundred/percent/capstone/Invoicify/utilities/ExcludeGeneratedFromJaCoCo.java
  src/test/java/com/hundred/percent/capstone/Invoicify/DatabaseConfigTest.java
Labels: Team_100_Percent

#37 Feature/ivoice1/rohit
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/controller/InvoiceController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/InvoiceDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/ItemDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/FeeType.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/InvoiceEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/ItemEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/repository/InvoiceRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/repository/ItemRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team1

#39 Issue 27 company list view
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyListViewDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
Labels: Team2

#43 Feature/ivoice1/rohit
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/entity/CompanyEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/repository/CompanyRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/controller/InvoiceController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/InvoiceDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/InvoiceEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/ItemEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/repository/InvoiceRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team1

#44 Issue 14 update company details
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/address/controller/AddressController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/dto/AddressDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/entity/AddressEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/repository/AddressRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/service/AddressService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyListViewDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/entity/CompanyEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
Labels: Team2

#48 Issue 45 address validation
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/address/controller/AddressController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/service/AddressService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/exception/CompanyDoesNotExistsException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/exception/CompanyExceptionHandler.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressServiceTest.java
Labels: Team2

#54 Feature/ivoice1/rohit
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/controller/InvoiceController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/InvoiceDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/InvoiceEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/PaidStatus.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/repository/InvoiceRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team1

#55 Issue 49 update address
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/address/controller/AddressController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/service/AddressService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressServiceTest.java
Labels: Team2

#59 Issue 56 company simple and list view bug
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/address/exception/AddressExceptionHandler.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/exception/CompanyAddressDoesNotExistsException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team2

#60 Issue 50 delete company
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
Labels: Team2

#62 Feature/issue 47 spring security
  build.gradle
  src/docs/asciidoc/security.adoc
  src/docs/asciidoc/security/authentication.adoc
  src/docs/asciidoc/security/employee.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/Employee.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/EmployeeController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/EmployeeRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/EmployeeService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtAuthorizationFilter.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtManager.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtToken.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/SecurityService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/SecurityUser.java
  src/main/java/com/hundred/percent/capstone/Invoicify/WebSecurityConfig.java
  src/main/resources/application.properties
  src/test/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplicationIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/securityTests/AuthenticationTests.java
  src/test/java/com/hundred/percent/capstone/Invoicify/securityTests/EmployeeTests.java
Labels: Team2

#63 Issue 51 delete address
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/address/controller/AddressController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/service/AddressService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressServiceTest.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
Labels: Team2

#65 Issue 61 change update company url
  README.md
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/resources/application-docker.properties
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
Labels: Team2

#67 Feature/ivoice1/rohit
  build.gradle
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/controller/InvoiceController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/InvoiceEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/CustomInvoiceException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/InvoiceWithoutCompanyException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/UnpaidInvoiceDeleteException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team1

#71 Issue 46 additional payload validation
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplication.java
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/controller/AddressController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/dto/AddressDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/service/AddressService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/entity/CompanyEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/exception/CompanyExceptionHandler.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/main/resources/application-heroku.properties
  src/main/resources/application.properties
  src/main/resources/public/error/400.html
  src/main/resources/public/error/401.html
  src/main/resources/public/error/404.html
  src/main/resources/public/error/500.html
  src/main/resources/public/error/error.html
  src/main/resources/public/home.html
  src/test/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplicationIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/address/AddressIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
Labels: Team2

#72 Feature/ivoice1/rohit
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/controller/InvoiceController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/InvoiceDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/CustomInvoiceException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/InvalidInputException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team2

#73 Feature/ivoice1/rohit
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team1

#74 Issue 64 code cleanup
  README.md
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/Employee.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/EmployeeController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/EmployeeRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Employee/EmployeeService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplication.java
  src/main/java/com/hundred/percent/capstone/Invoicify/InvoicifyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtAuthorizationFilter.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtManager.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/Jwt/JwtToken.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/SecurityService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/Security/SecurityUser.java
  src/main/java/com/hundred/percent/capstone/Invoicify/WebSecurityConfig.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/controller/AddressController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/dto/AddressDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/entity/AddressEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/exception/AddressExceptionHandler.java
  src/main/java/com/hundred/percent/capstone/Invoicify/address/service/AddressService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/controller/CompanyController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanyListViewDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/dto/CompanySimpleViewDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/exception/CompanyDoesNotExistsException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/exception/CompanyExceptionHandler.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/repository/CompanyRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/company/service/CompanyService.java
  src/main/java/com/hundred/percent/capstone/Invoicify/config/DatabaseConfig.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/controller/InvoiceController.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/InvoiceDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/dto/ItemDTO.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/FeeType.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/InvoiceEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/ItemEntity.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/entity/PaidStatus.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/CustomInvoiceException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/InvalidInputException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/InvoiceWithoutCompanyException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/exception/UnpaidInvoiceDeleteException.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/repository/InvoiceRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/repository/ItemRepository.java
  src/main/java/com/hundred/percent/capstone/Invoicify/invoice/service/InvoiceService.java
  src/test/java/com/hundred/percent/capstone/Invoicify/InvoicifyApplicationIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/company/CompanyServiceTest.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceIT.java
  src/test/java/com/hundred/percent/capstone/Invoicify/invoice/InvoiceServiceTest.java
Labels: Team2
